[project]
name = "msmc"
version = "0.1.0"
authors = [
    {name = "Arsalan Jawaid"},
]
readme = "README.md"
requires-python = ">=3.11"
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    "numpy",
    "scipy",
]

[dependency-groups]
dev = [
    "pre-commit>=2.8.2",
    "matplotlib>=3.7.2",
    "nanobind>=2.12.0",
    "pytest>=8.0",
]

[build-system]
requires = ["scikit-build-core>=0.10", "nanobind>=2.0"]
build-backend = "scikit_build_core.build"

[tool.scikit-build]
minimum-version = "build-system.requires"
wheel.packages = ["src/msmc"]
wheel.py-api = "cp312"
build-dir = "build/{wheel_tag}"
cmake.build-type = "Debug"
